name: fitness_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.5
  path: ^1.8.2
  intl: ^0.18.0
  flutter_rating_bar: ^4.0.1
  permission_handler: ^10.2.0
  flutter_sound_lite: ^8.5.0
  audioplayers: ^3.0.1
  path_provider: ^2.0.13
  table_calendar: ^3.0.9
  google_speech: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/service_account/
  uses-material-design: true
